//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace w2.BBS.Manager
{


	public partial class Login
	{

		/// <summary>
		/// pnlError control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Panel pnlError;

		/// <summary>
		/// lError control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Literal lError;

		/// <summary>
		/// tbLoginId control.
		/// </summary>
		protected global::System.Web.UI.WebControls.TextBox tbLoginId;

		/// <summary>
		/// tbPassword control.
		/// </summary>
		protected global::System.Web.UI.WebControls.TextBox tbPassword;

		/// <summary>
		/// lbLogin control.
		/// </summary>
		protected global::System.Web.UI.WebControls.LinkButton lbLogin;
	}
}
