//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace w2.BBS.Manager
{
	public partial class PostList
	{
		/// <summary>
		/// tbSearchKeyword control.
		/// </summary>
		protected global::System.Web.UI.WebControls.TextBox tbSearchKeyword;

		/// <summary>
		/// lbSearch control.
		/// </summary>
		protected global::System.Web.UI.WebControls.LinkButton lbSearch;

		/// <summary>
		/// lbSearchClear control.
		/// </summary>
		protected global::System.Web.UI.WebControls.LinkButton lbSearchClear;

		/// <summary>
		/// rPosts control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Repeater rPosts;

		/// <summary>
		/// rReplies control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Repeater rReplies;
	}
}
