//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace w2.BBS.Manager
{
	public partial class UserDetail
	{
		/// <summary>
		/// pnlNotFound control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Panel pnlNotFound;

		/// <summary>
		/// pnlProfile control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Panel pnlProfile;

		/// <summary>
		/// lUserId control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Literal lUserId;

		/// <summary>
		/// lLoginId control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Literal lLoginId;

		/// <summary>
		/// lUserName control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Literal lUserName;

		/// <summary>
		/// rPosts control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Repeater rPosts;

		/// <summary>
		/// rReplies control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Repeater rReplies;

		/// <summary>
		/// lbBack control.
		/// </summary>
		protected global::System.Web.UI.WebControls.LinkButton lbBack;
	}
}
