//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace w2.BBS.Manager
{
	public partial class UserEdit
	{
		/// <summary>
		/// pnlMsg control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Panel pnlMsg;

		/// <summary>
		/// lMsg control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Literal lMsg;

		/// <summary>
		/// lLoginId control.
		/// </summary>
		protected global::System.Web.UI.WebControls.Literal lLoginId;

		/// <summary>
		/// tbUserName control.
		/// </summary>
		protected global::System.Web.UI.WebControls.TextBox tbUserName;

		/// <summary>
		/// tbPassword control.
		/// </summary>
		protected global::System.Web.UI.WebControls.TextBox tbPassword;

		/// <summary>
		/// lbSave control.
		/// </summary>
		protected global::System.Web.UI.WebControls.LinkButton lbSave;

		/// <summary>
		/// lbDeleteUser control.
		/// </summary>
		protected global::System.Web.UI.WebControls.LinkButton lbDeleteUser;

		/// <summary>
		/// lbBack control.
		/// </summary>
		protected global::System.Web.UI.WebControls.LinkButton lbBack;
	}
}
