//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace w2.BBS.Manager.Form.Common
{


	public partial class Default
	{

		/// <summary>
		/// head control.
		/// </summary>
		protected global::System.Web.UI.WebControls.ContentPlaceHolder head;

		/// <summary>
		/// form1 control.
		/// </summary>
		protected global::System.Web.UI.HtmlControls.HtmlForm form1;

		/// <summary>
		/// lbNavUserList control.
		/// </summary>
		protected global::System.Web.UI.WebControls.LinkButton lbNavUserList;

		/// <summary>
		/// lbNavPostList control.
		/// </summary>
		protected global::System.Web.UI.WebControls.LinkButton lbNavPostList;

		/// <summary>
		/// lbNavLogout control.
		/// </summary>
		protected global::System.Web.UI.WebControls.LinkButton lbNavLogout;

		/// <summary>
		/// ContentPlaceHolder1 control.
		/// </summary>
		protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
	}
}
